package org.apiminer.entities.example;

public enum ExampleMetric {
	LOC, 
	DECISION_STATEMENTS, 
	INVOCATIONS, 
	ARGUMENTS, 
	PRIMITIVE_ARGUMENTS, 
	NULL_ARGUMENTS, 
	FIELD_ARGUMENTS,
	UNDISCOVERED_DECLARATIONS,
	UNHANDLED_EXCEPTIONS;
}
